export type MedSchool = {
  id: string;
  name: string;
  school: string;
  loc: string;
  rank: number;
  acceptRate: number;
  tuition: number;
  classSize: number;
  medianMCAT: number;
  medianGPA: number;
  matchRate: number;
  primaryCarePct: number;
  researchFunding: number; // NIH funding $M
  focus: "Research" | "Primary Care" | "Balanced";
  topResidencies: string[];
  inStateRequired: boolean;
  color: string;
  tier: 1 | 2 | 3;
  summary?: string;
};

// Top 60 US medical schools — research and primary care leaders
export const medSchools: MedSchool[] = [
  { id: "harvard-med", name: "Harvard Medical School", school: "Harvard University", loc: "Boston, MA", rank: 1, acceptRate: 3.3, tuition: 69300, classSize: 165, medianMCAT: 521, medianGPA: 3.94, matchRate: 99, primaryCarePct: 32, researchFunding: 654, focus: "Research", topResidencies: ["MGH", "Brigham", "Mayo Clinic", "Stanford"], inStateRequired: false, color: "#A51C30", tier: 1, summary: "The most research-intensive med school on Earth. MGH and Brigham residencies + the deepest physician-scientist pipeline in the world." },
  { id: "jhu-med", name: "Johns Hopkins School of Medicine", school: "Johns Hopkins University", loc: "Baltimore, MD", rank: 2, acceptRate: 6.0, tuition: 60340, classSize: 120, medianMCAT: 521, medianGPA: 3.94, matchRate: 99, primaryCarePct: 28, researchFunding: 595, focus: "Research", topResidencies: ["JHH", "MGH", "UCSF", "Penn"], inStateRequired: false, color: "#68ACE5", tier: 1, summary: "Birthplace of modern medical education. Johns Hopkins Hospital is consistently the top US hospital; residency placement is unmatched." },
  { id: "ucsf-med", name: "UCSF School of Medicine", school: "UC San Francisco", loc: "San Francisco, CA", rank: 3, acceptRate: 3.5, tuition: 41000, classSize: 165, medianMCAT: 518, medianGPA: 3.85, matchRate: 99, primaryCarePct: 33, researchFunding: 803, focus: "Research", topResidencies: ["UCSF", "Stanford", "MGH", "JHH"], inStateRequired: false, color: "#052049", tier: 1, summary: "#1 NIH-funded med school. UCSF Medical Center plus the most progressive curriculum in the country." },
  { id: "penn-med", name: "Perelman School of Medicine", school: "University of Pennsylvania", loc: "Philadelphia, PA", rank: 4, acceptRate: 4.4, tuition: 65610, classSize: 155, medianMCAT: 521, medianGPA: 3.93, matchRate: 99, primaryCarePct: 25, researchFunding: 587, focus: "Research", topResidencies: ["HUP", "JHH", "MGH", "Brigham"], inStateRequired: false, color: "#011F5B", tier: 1, summary: "America's first medical school. Strong gene-therapy and oncology focus; consistent top-5 NIH funder." },
  { id: "duke-med", name: "Duke University School of Medicine", school: "Duke University", loc: "Durham, NC", rank: 5, acceptRate: 3.8, tuition: 70000, classSize: 120, medianMCAT: 519, medianGPA: 3.88, matchRate: 99, primaryCarePct: 27, researchFunding: 460, focus: "Research", topResidencies: ["Duke", "MGH", "Stanford", "JHH"], inStateRequired: false, color: "#003087", tier: 1, summary: "Unique 1-year clinical curriculum. Strong cardiology and Duke University Hospital placement." },
  { id: "columbia-vps", name: "Vagelos College of Physicians and Surgeons", school: "Columbia University", loc: "New York, NY", rank: 6, acceptRate: 3.6, tuition: 70210, classSize: 145, medianMCAT: 521, medianGPA: 3.91, matchRate: 99, primaryCarePct: 24, researchFunding: 525, focus: "Research", topResidencies: ["NewYork-Presbyterian", "Mt. Sinai", "MGH", "JHH"], inStateRequired: false, color: "#B9D9EB", tier: 1, summary: "Founded 1767 — second-oldest US med school. NewYork-Presbyterian is one of the country's largest academic medical centers." },
  { id: "stanford-med", name: "Stanford School of Medicine", school: "Stanford University", loc: "Stanford, CA", rank: 7, acceptRate: 2.3, tuition: 67424, classSize: 90, medianMCAT: 519, medianGPA: 3.89, matchRate: 99, primaryCarePct: 22, researchFunding: 487, focus: "Research", topResidencies: ["Stanford", "UCSF", "MGH", "JHH"], inStateRequired: false, color: "#8C1515", tier: 1, summary: "Smallest elite med school. The biotech and AI-in-medicine pipeline runs through here; Silicon Valley access is unique." },
  { id: "wustl-med", name: "WashU School of Medicine", school: "Washington University in St. Louis", loc: "St. Louis, MO", rank: 8, acceptRate: 7.4, tuition: 71500, classSize: 125, medianMCAT: 522, medianGPA: 3.91, matchRate: 99, primaryCarePct: 26, researchFunding: 555, focus: "Research", topResidencies: ["BJH", "MGH", "JHH", "UCSF"], inStateRequired: false, color: "#A51417", tier: 1, summary: "Highest median MCAT of any US medical school. Barnes-Jewish Hospital ranks consistently in the top 10 nationally." },
  { id: "yale-med", name: "Yale School of Medicine", school: "Yale University", loc: "New Haven, CT", rank: 9, acceptRate: 5.5, tuition: 70470, classSize: 105, medianMCAT: 519, medianGPA: 3.88, matchRate: 99, primaryCarePct: 23, researchFunding: 433, focus: "Research", topResidencies: ["Yale-New Haven", "MGH", "JHH", "UCSF"], inStateRequired: false, color: "#0F4D92", tier: 1, summary: "Famously pass/fail with no class rank. The 'Yale System' attracts students who want to focus on research, not grades." },
  { id: "weill-cornell", name: "Weill Cornell Medical College", school: "Cornell University", loc: "New York, NY", rank: 10, acceptRate: 4.4, tuition: 70250, classSize: 110, medianMCAT: 519, medianGPA: 3.92, matchRate: 99, primaryCarePct: 24, researchFunding: 312, focus: "Research", topResidencies: ["NewYork-Presbyterian", "MSK", "Mt. Sinai", "MGH"], inStateRequired: false, color: "#B31B1B", tier: 1, summary: "Direct partnership with Memorial Sloan Kettering. Strongest oncology training in NYC and one of the deepest in the world." },
  { id: "mayo-alix", name: "Mayo Clinic Alix School of Medicine", school: "Mayo Clinic", loc: "Rochester, MN", rank: 11, acceptRate: 2.0, tuition: 60100, classSize: 100, medianMCAT: 520, medianGPA: 3.95, matchRate: 100, primaryCarePct: 28, researchFunding: 245, focus: "Research", topResidencies: ["Mayo", "MGH", "JHH", "UCSF"], inStateRequired: false, color: "#0058A0", tier: 1, summary: "The Mayo Clinic itself. Tiny class (~50 per campus), full-tuition scholarships for many; the most prestigious clinical training in the country." },
  { id: "nyu-grossman", name: "NYU Grossman School of Medicine", school: "New York University", loc: "New York, NY", rank: 12, acceptRate: 2.5, tuition: 0, classSize: 110, medianMCAT: 522, medianGPA: 3.96, matchRate: 99, primaryCarePct: 21, researchFunding: 305, focus: "Research", topResidencies: ["NYU Langone", "MGH", "JHH", "UCSF"], inStateRequired: false, color: "#57068C", tier: 1, summary: "Free tuition for all admitted students — first US med school to do this at scale (since 2018). Selectivity has skyrocketed." },
  { id: "michigan-med", name: "University of Michigan Medical School", school: "University of Michigan", loc: "Ann Arbor, MI", rank: 13, acceptRate: 6.5, tuition: 50920, classSize: 175, medianMCAT: 516, medianGPA: 3.85, matchRate: 99, primaryCarePct: 32, researchFunding: 502, focus: "Research", topResidencies: ["U Michigan", "MGH", "JHH", "UCSF"], inStateRequired: false, color: "#00274C", tier: 1 },
  { id: "ucla-geffen", name: "David Geffen School of Medicine at UCLA", school: "UCLA", loc: "Los Angeles, CA", rank: 14, acceptRate: 2.4, tuition: 41700, classSize: 175, medianMCAT: 517, medianGPA: 3.87, matchRate: 99, primaryCarePct: 35, researchFunding: 567, focus: "Research", topResidencies: ["UCLA", "Cedars-Sinai", "UCSF", "Stanford"], inStateRequired: false, color: "#2774AE", tier: 1 },
  { id: "pittsburgh-med", name: "University of Pittsburgh School of Medicine", school: "University of Pittsburgh", loc: "Pittsburgh, PA", rank: 15, acceptRate: 5.4, tuition: 64360, classSize: 150, medianMCAT: 518, medianGPA: 3.84, matchRate: 99, primaryCarePct: 31, researchFunding: 671, focus: "Research", topResidencies: ["UPMC", "MGH", "JHH", "UCSF"], inStateRequired: false, color: "#003594", tier: 1 },
  { id: "feinberg-med", name: "Northwestern Feinberg School of Medicine", school: "Northwestern University", loc: "Chicago, IL", rank: 16, acceptRate: 4.6, tuition: 70512, classSize: 165, medianMCAT: 521, medianGPA: 3.92, matchRate: 99, primaryCarePct: 27, researchFunding: 410, focus: "Research", topResidencies: ["Northwestern", "MGH", "JHH", "UCSF"], inStateRequired: false, color: "#4E2A84", tier: 1 },
  { id: "pritzker-med", name: "Pritzker School of Medicine", school: "University of Chicago", loc: "Chicago, IL", rank: 17, acceptRate: 4.5, tuition: 67923, classSize: 90, medianMCAT: 519, medianGPA: 3.92, matchRate: 99, primaryCarePct: 28, researchFunding: 280, focus: "Research", topResidencies: ["UChicago", "MGH", "JHH", "Stanford"], inStateRequired: false, color: "#800000", tier: 1 },
  { id: "baylor-med", name: "Baylor College of Medicine", school: "Baylor College of Medicine", loc: "Houston, TX", rank: 18, acceptRate: 4.5, tuition: 26770, classSize: 185, medianMCAT: 519, medianGPA: 3.91, matchRate: 99, primaryCarePct: 29, researchFunding: 478, focus: "Research", topResidencies: ["Texas Med Center", "MGH", "JHH", "Mayo"], inStateRequired: false, color: "#003366", tier: 1, summary: "Texas Medical Center is the largest medical complex in the world. Best value-to-prestige ratio of any top-20 program." },
  { id: "vanderbilt-med", name: "Vanderbilt University School of Medicine", school: "Vanderbilt University", loc: "Nashville, TN", rank: 19, acceptRate: 4.3, tuition: 64760, classSize: 95, medianMCAT: 521, medianGPA: 3.91, matchRate: 99, primaryCarePct: 30, researchFunding: 470, focus: "Research", topResidencies: ["VUMC", "MGH", "JHH", "Mayo"], inStateRequired: false, color: "#866D4B", tier: 1 },
  { id: "icahn-mt-sinai", name: "Icahn School of Medicine at Mount Sinai", school: "Mount Sinai", loc: "New York, NY", rank: 20, acceptRate: 5.5, tuition: 63290, classSize: 140, medianMCAT: 519, medianGPA: 3.89, matchRate: 99, primaryCarePct: 28, researchFunding: 458, focus: "Research", topResidencies: ["Mt. Sinai", "NYU", "MGH", "JHH"], inStateRequired: false, color: "#E03A3E", tier: 1 },
  { id: "utsw-med", name: "UT Southwestern Medical School", school: "UT Southwestern", loc: "Dallas, TX", rank: 21, acceptRate: 8.6, tuition: 23700, classSize: 235, medianMCAT: 519, medianGPA: 3.91, matchRate: 99, primaryCarePct: 32, researchFunding: 498, focus: "Research", topResidencies: ["UTSW", "MGH", "JHH", "Mayo"], inStateRequired: true, color: "#005EB8", tier: 1, summary: "Highest research output per dollar of any med school. 6 Nobel laureates on faculty; in-state tuition under $25k." },
  { id: "emory-med", name: "Emory University School of Medicine", school: "Emory University", loc: "Atlanta, GA", rank: 22, acceptRate: 5.6, tuition: 56450, classSize: 145, medianMCAT: 517, medianGPA: 3.85, matchRate: 99, primaryCarePct: 31, researchFunding: 485, focus: "Research", topResidencies: ["Emory", "MGH", "JHH", "Mayo"], inStateRequired: false, color: "#012169", tier: 1, summary: "Direct CDC partnership and strong global health programs. Atlanta's hospital network rivals Boston's." },
  { id: "unc-med", name: "UNC School of Medicine", school: "UNC Chapel Hill", loc: "Chapel Hill, NC", rank: 23, acceptRate: 4.7, tuition: 39990, classSize: 190, medianMCAT: 514, medianGPA: 3.85, matchRate: 99, primaryCarePct: 38, researchFunding: 380, focus: "Balanced", topResidencies: ["UNC", "Duke", "Wake Forest", "MGH"], inStateRequired: true, color: "#4B9CD3", tier: 1, summary: "Top public med school for primary care. Strong rural medicine pipeline; 80% in-state acceptance preference." },
  { id: "case-western-med", name: "Case Western Reserve School of Medicine", school: "Case Western Reserve", loc: "Cleveland, OH", rank: 24, acceptRate: 7.6, tuition: 70000, classSize: 215, medianMCAT: 517, medianGPA: 3.83, matchRate: 99, primaryCarePct: 30, researchFunding: 460, focus: "Research", topResidencies: ["Cleveland Clinic", "UH Cleveland", "MGH", "JHH"], inStateRequired: false, color: "#0A304E", tier: 1 },
  { id: "bu-chobanian", name: "BU Chobanian & Avedisian School of Medicine", school: "Boston University", loc: "Boston, MA", rank: 25, acceptRate: 4.7, tuition: 68530, classSize: 165, medianMCAT: 517, medianGPA: 3.78, matchRate: 99, primaryCarePct: 32, researchFunding: 365, focus: "Research", topResidencies: ["Boston Med Ctr", "MGH", "JHH", "Mayo"], inStateRequired: false, color: "#CC0000", tier: 1 },
  { id: "wisconsin-med", name: "University of Wisconsin School of Medicine and Public Health", school: "UW-Madison", loc: "Madison, WI", rank: 26, acceptRate: 5.0, tuition: 39000, classSize: 175, medianMCAT: 514, medianGPA: 3.83, matchRate: 99, primaryCarePct: 35, researchFunding: 312, focus: "Balanced", topResidencies: ["UW Hospital", "MGH", "Mayo", "Cleveland Clinic"], inStateRequired: true, color: "#C5050C", tier: 2 },
  { id: "indiana-med", name: "Indiana University School of Medicine", school: "Indiana University", loc: "Indianapolis, IN", rank: 27, acceptRate: 9.0, tuition: 39400, classSize: 365, medianMCAT: 511, medianGPA: 3.82, matchRate: 98, primaryCarePct: 36, researchFunding: 290, focus: "Balanced", topResidencies: ["IU Health", "Mayo", "MGH", "Cleveland Clinic"], inStateRequired: true, color: "#990000", tier: 2, summary: "Largest single-campus med school in the US (~360 per class). Strong primary care and Indianapolis hospital network." },
  { id: "iowa-carver", name: "Carver College of Medicine", school: "University of Iowa", loc: "Iowa City, IA", rank: 28, acceptRate: 5.1, tuition: 37000, classSize: 150, medianMCAT: 513, medianGPA: 3.85, matchRate: 99, primaryCarePct: 38, researchFunding: 295, focus: "Balanced", topResidencies: ["UIHC", "Mayo", "MGH", "Cleveland Clinic"], inStateRequired: true, color: "#FFCD00", tier: 2 },
  { id: "minnesota-med", name: "University of Minnesota Medical School", school: "University of Minnesota", loc: "Minneapolis, MN", rank: 29, acceptRate: 6.0, tuition: 46000, classSize: 240, medianMCAT: 511, medianGPA: 3.74, matchRate: 99, primaryCarePct: 38, researchFunding: 360, focus: "Balanced", topResidencies: ["UMN", "Mayo", "MGH", "JHH"], inStateRequired: true, color: "#7A0019", tier: 2 },
  { id: "ohio-state-med", name: "Ohio State College of Medicine", school: "Ohio State University", loc: "Columbus, OH", rank: 30, acceptRate: 5.5, tuition: 39800, classSize: 200, medianMCAT: 514, medianGPA: 3.83, matchRate: 99, primaryCarePct: 33, researchFunding: 320, focus: "Balanced", topResidencies: ["OSU Wexner", "Cleveland Clinic", "MGH", "JHH"], inStateRequired: true, color: "#BB0000", tier: 2 },
  { id: "alpert-med", name: "Warren Alpert Medical School", school: "Brown University", loc: "Providence, RI", rank: 31, acceptRate: 3.0, tuition: 67750, classSize: 145, medianMCAT: 513, medianGPA: 3.78, matchRate: 99, primaryCarePct: 33, researchFunding: 235, focus: "Balanced", topResidencies: ["Rhode Island Hospital", "MGH", "JHH", "Mayo"], inStateRequired: false, color: "#4E3629", tier: 2 },
  { id: "keck-med", name: "Keck School of Medicine of USC", school: "USC", loc: "Los Angeles, CA", rank: 32, acceptRate: 4.0, tuition: 75900, classSize: 185, medianMCAT: 517, medianGPA: 3.78, matchRate: 99, primaryCarePct: 28, researchFunding: 322, focus: "Research", topResidencies: ["LAC+USC", "Cedars-Sinai", "UCLA", "MGH"], inStateRequired: false, color: "#990000", tier: 2 },
  { id: "uva-med", name: "University of Virginia School of Medicine", school: "University of Virginia", loc: "Charlottesville, VA", rank: 33, acceptRate: 8.7, tuition: 54300, classSize: 160, medianMCAT: 517, medianGPA: 3.93, matchRate: 99, primaryCarePct: 32, researchFunding: 195, focus: "Balanced", topResidencies: ["UVA Health", "JHH", "MGH", "Duke"], inStateRequired: true, color: "#232D4B", tier: 2 },
  { id: "maryland-med", name: "University of Maryland School of Medicine", school: "University of Maryland", loc: "Baltimore, MD", rank: 34, acceptRate: 6.2, tuition: 42500, classSize: 160, medianMCAT: 513, medianGPA: 3.85, matchRate: 99, primaryCarePct: 33, researchFunding: 460, focus: "Research", topResidencies: ["UMMC", "JHH", "MGH", "Mayo"], inStateRequired: true, color: "#E03A3E", tier: 2 },
  { id: "ufl-med", name: "University of Florida College of Medicine", school: "University of Florida", loc: "Gainesville, FL", rank: 35, acceptRate: 6.5, tuition: 36800, classSize: 135, medianMCAT: 514, medianGPA: 3.81, matchRate: 99, primaryCarePct: 33, researchFunding: 250, focus: "Balanced", topResidencies: ["UF Health", "Mayo", "Emory", "MGH"], inStateRequired: true, color: "#FA4616", tier: 2 },
  { id: "miller-med", name: "Miller School of Medicine", school: "University of Miami", loc: "Miami, FL", rank: 36, acceptRate: 4.5, tuition: 50250, classSize: 200, medianMCAT: 513, medianGPA: 3.79, matchRate: 99, primaryCarePct: 31, researchFunding: 215, focus: "Balanced", topResidencies: ["Jackson Memorial", "Emory", "Duke", "MGH"], inStateRequired: false, color: "#F47321", tier: 2 },
  { id: "tulane-med", name: "Tulane University School of Medicine", school: "Tulane University", loc: "New Orleans, LA", rank: 37, acceptRate: 6.0, tuition: 73600, classSize: 200, medianMCAT: 511, medianGPA: 3.71, matchRate: 98, primaryCarePct: 35, researchFunding: 95, focus: "Primary Care", topResidencies: ["Tulane", "Ochsner", "MGH", "Emory"], inStateRequired: false, color: "#418FDE", tier: 3 },
  { id: "einstein-med", name: "Albert Einstein College of Medicine", school: "Yeshiva University", loc: "Bronx, NY", rank: 38, acceptRate: 4.0, tuition: 0, classSize: 185, medianMCAT: 515, medianGPA: 3.78, matchRate: 99, primaryCarePct: 32, researchFunding: 245, focus: "Research", topResidencies: ["Montefiore", "Mt. Sinai", "NYP", "MGH"], inStateRequired: false, color: "#003366", tier: 2, summary: "Free tuition since 2024 (Ruth Gottesman gift). Massive Bronx clinical exposure; one of the country's most diverse patient populations." },
  { id: "georgetown-med", name: "Georgetown University School of Medicine", school: "Georgetown University", loc: "Washington, DC", rank: 39, acceptRate: 2.6, tuition: 67392, classSize: 200, medianMCAT: 513, medianGPA: 3.74, matchRate: 99, primaryCarePct: 30, researchFunding: 95, focus: "Balanced", topResidencies: ["MedStar Georgetown", "JHH", "MGH", "Mayo"], inStateRequired: false, color: "#063462", tier: 2 },
  { id: "tufts-med", name: "Tufts University School of Medicine", school: "Tufts University", loc: "Boston, MA", rank: 40, acceptRate: 4.4, tuition: 71500, classSize: 200, medianMCAT: 514, medianGPA: 3.74, matchRate: 99, primaryCarePct: 32, researchFunding: 110, focus: "Balanced", topResidencies: ["Tufts MC", "Boston MC", "MGH", "Brigham"], inStateRequired: false, color: "#3E8EDE", tier: 2 },
  { id: "umass-chan", name: "UMass Chan Medical School", school: "UMass Chan", loc: "Worcester, MA", rank: 41, acceptRate: 7.0, tuition: 38260, classSize: 165, medianMCAT: 513, medianGPA: 3.78, matchRate: 99, primaryCarePct: 38, researchFunding: 215, focus: "Primary Care", topResidencies: ["UMass Memorial", "MGH", "Brigham", "Tufts"], inStateRequired: true, color: "#822433", tier: 2, summary: "Best primary-care med school in New England. ~95% Massachusetts residents; in-state tuition is exceptional value." },
  { id: "psu-hershey", name: "Penn State College of Medicine", school: "Penn State Hershey", loc: "Hershey, PA", rank: 42, acceptRate: 4.0, tuition: 51000, classSize: 150, medianMCAT: 512, medianGPA: 3.83, matchRate: 99, primaryCarePct: 35, researchFunding: 150, focus: "Balanced", topResidencies: ["Hershey Med", "MGH", "JHH", "Cleveland Clinic"], inStateRequired: false, color: "#1E407C", tier: 2 },
  { id: "rochester-med", name: "University of Rochester School of Medicine", school: "University of Rochester", loc: "Rochester, NY", rank: 43, acceptRate: 5.0, tuition: 68080, classSize: 110, medianMCAT: 514, medianGPA: 3.81, matchRate: 99, primaryCarePct: 32, researchFunding: 180, focus: "Balanced", topResidencies: ["Strong Memorial", "MGH", "JHH", "Mayo"], inStateRequired: false, color: "#FFD100", tier: 2 },
  { id: "geisel-med", name: "Geisel School of Medicine at Dartmouth", school: "Dartmouth College", loc: "Hanover, NH", rank: 44, acceptRate: 3.0, tuition: 71820, classSize: 95, medianMCAT: 514, medianGPA: 3.79, matchRate: 99, primaryCarePct: 33, researchFunding: 90, focus: "Balanced", topResidencies: ["Dartmouth Hitchcock", "MGH", "Brigham", "Mayo"], inStateRequired: false, color: "#00693E", tier: 2 },
  { id: "drexel-med", name: "Drexel University College of Medicine", school: "Drexel University", loc: "Philadelphia, PA", rank: 45, acceptRate: 4.0, tuition: 65860, classSize: 260, medianMCAT: 511, medianGPA: 3.71, matchRate: 99, primaryCarePct: 32, researchFunding: 75, focus: "Balanced", topResidencies: ["Hahnemann/Drexel", "Penn", "JHH", "Mayo"], inStateRequired: false, color: "#07294D", tier: 3 },
  { id: "loyola-stritch", name: "Stritch School of Medicine", school: "Loyola University Chicago", loc: "Maywood, IL", rank: 46, acceptRate: 3.0, tuition: 64800, classSize: 175, medianMCAT: 511, medianGPA: 3.74, matchRate: 99, primaryCarePct: 33, researchFunding: 35, focus: "Primary Care", topResidencies: ["Loyola", "Northwestern", "Rush", "MGH"], inStateRequired: false, color: "#660033", tier: 3 },
  { id: "rush-med", name: "Rush Medical College", school: "Rush University", loc: "Chicago, IL", rank: 47, acceptRate: 2.5, tuition: 64500, classSize: 140, medianMCAT: 511, medianGPA: 3.74, matchRate: 99, primaryCarePct: 36, researchFunding: 90, focus: "Primary Care", topResidencies: ["Rush", "Northwestern", "UChicago", "Mayo"], inStateRequired: false, color: "#006747", tier: 3 },
  { id: "jefferson-med", name: "Sidney Kimmel Medical College", school: "Thomas Jefferson University", loc: "Philadelphia, PA", rank: 48, acceptRate: 5.0, tuition: 64500, classSize: 270, medianMCAT: 510, medianGPA: 3.72, matchRate: 99, primaryCarePct: 33, researchFunding: 90, focus: "Balanced", topResidencies: ["Jefferson", "Penn", "JHH", "MGH"], inStateRequired: false, color: "#00467F", tier: 3 },
  { id: "wake-med", name: "Wake Forest University School of Medicine", school: "Wake Forest University", loc: "Winston-Salem, NC", rank: 49, acceptRate: 3.5, tuition: 67268, classSize: 145, medianMCAT: 514, medianGPA: 3.74, matchRate: 99, primaryCarePct: 32, researchFunding: 215, focus: "Balanced", topResidencies: ["Atrium Wake Forest", "Duke", "MGH", "Mayo"], inStateRequired: false, color: "#9E7E38", tier: 2 },
  { id: "ohsu-med", name: "Oregon Health & Science University School of Medicine", school: "OHSU", loc: "Portland, OR", rank: 50, acceptRate: 4.0, tuition: 49600, classSize: 155, medianMCAT: 513, medianGPA: 3.74, matchRate: 99, primaryCarePct: 38, researchFunding: 305, focus: "Primary Care", topResidencies: ["OHSU", "UW Med", "UCSF", "Stanford"], inStateRequired: true, color: "#0E4D92", tier: 2, summary: "#1 primary-care med school in the country (US News). Strong rural medicine and family medicine focus." },
  { id: "anschutz-med", name: "Colorado School of Medicine", school: "University of Colorado Anschutz", loc: "Aurora, CO", rank: 51, acceptRate: 3.4, tuition: 47900, classSize: 185, medianMCAT: 513, medianGPA: 3.78, matchRate: 99, primaryCarePct: 35, researchFunding: 332, focus: "Balanced", topResidencies: ["UCH", "Children's Colorado", "Mayo", "MGH"], inStateRequired: true, color: "#A2A4A1", tier: 2 },
  { id: "uw-med", name: "University of Washington School of Medicine", school: "University of Washington", loc: "Seattle, WA", rank: 52, acceptRate: 3.7, tuition: 39000, classSize: 285, medianMCAT: 510, medianGPA: 3.79, matchRate: 99, primaryCarePct: 50, researchFunding: 545, focus: "Primary Care", topResidencies: ["UW Medicine", "Harborview", "Mayo", "MGH"], inStateRequired: true, color: "#4B2E83", tier: 1, summary: "WWAMI program serves Wash/Wyoming/Alaska/Montana/Idaho. #1 in primary care training and rural medicine." },
  { id: "ucdavis-med", name: "UC Davis School of Medicine", school: "UC Davis", loc: "Sacramento, CA", rank: 53, acceptRate: 2.5, tuition: 41700, classSize: 130, medianMCAT: 511, medianGPA: 3.66, matchRate: 99, primaryCarePct: 42, researchFunding: 220, focus: "Primary Care", topResidencies: ["UC Davis", "UCSF", "Stanford", "UCLA"], inStateRequired: true, color: "#022851", tier: 2 },
  { id: "unm-med", name: "University of New Mexico School of Medicine", school: "University of New Mexico", loc: "Albuquerque, NM", rank: 54, acceptRate: 9.0, tuition: 21000, classSize: 110, medianMCAT: 506, medianGPA: 3.76, matchRate: 98, primaryCarePct: 50, researchFunding: 75, focus: "Primary Care", topResidencies: ["UNM", "U Utah", "Mayo", "Stanford"], inStateRequired: true, color: "#BA0C2F", tier: 3, summary: "Underrated primary care school with deep tribal/rural pipeline. Very low in-state tuition." },
  { id: "nebraska-med", name: "University of Nebraska College of Medicine", school: "University of Nebraska", loc: "Omaha, NE", rank: 55, acceptRate: 5.0, tuition: 33500, classSize: 130, medianMCAT: 510, medianGPA: 3.84, matchRate: 99, primaryCarePct: 45, researchFunding: 110, focus: "Primary Care", topResidencies: ["Nebraska Med", "Mayo", "Cleveland Clinic", "MGH"], inStateRequired: true, color: "#D00000", tier: 3 },
  { id: "und-med", name: "UND School of Medicine and Health Sciences", school: "University of North Dakota", loc: "Grand Forks, ND", rank: 56, acceptRate: 7.0, tuition: 36000, classSize: 80, medianMCAT: 502, medianGPA: 3.74, matchRate: 99, primaryCarePct: 55, researchFunding: 30, focus: "Primary Care", topResidencies: ["UND", "Mayo", "Sanford", "Cleveland Clinic"], inStateRequired: true, color: "#009A44", tier: 3 },
  { id: "brody-med", name: "Brody School of Medicine", school: "East Carolina University", loc: "Greenville, NC", rank: 57, acceptRate: 6.0, tuition: 18000, classSize: 85, medianMCAT: 506, medianGPA: 3.75, matchRate: 99, primaryCarePct: 55, researchFunding: 22, focus: "Primary Care", topResidencies: ["ECU/Vidant", "UNC", "Duke", "Wake Forest"], inStateRequired: true, color: "#592A8A", tier: 3, summary: "100% in-state focus. Designed specifically to feed primary care into rural NC; tuition is the lowest in the country." },
  { id: "mercer-med", name: "Mercer University School of Medicine", school: "Mercer University", loc: "Macon, GA", rank: 58, acceptRate: 12.0, tuition: 50800, classSize: 140, medianMCAT: 506, medianGPA: 3.71, matchRate: 99, primaryCarePct: 50, researchFunding: 18, focus: "Primary Care", topResidencies: ["Mercer", "Emory", "Wake Forest", "MUSC"], inStateRequired: true, color: "#FF7F00", tier: 3 },
  { id: "musc-med", name: "Medical University of South Carolina", school: "MUSC", loc: "Charleston, SC", rank: 59, acceptRate: 9.0, tuition: 41000, classSize: 180, medianMCAT: 510, medianGPA: 3.75, matchRate: 99, primaryCarePct: 38, researchFunding: 240, focus: "Balanced", topResidencies: ["MUSC", "Emory", "Wake Forest", "Duke"], inStateRequired: true, color: "#73000A", tier: 3 },
  { id: "uab-med", name: "UAB Heersink School of Medicine", school: "University of Alabama at Birmingham", loc: "Birmingham, AL", rank: 60, acceptRate: 10.0, tuition: 32500, classSize: 195, medianMCAT: 512, medianGPA: 3.83, matchRate: 99, primaryCarePct: 35, researchFunding: 397, focus: "Balanced", topResidencies: ["UAB", "Vanderbilt", "Emory", "MGH"], inStateRequired: true, color: "#1E6B52", tier: 2 },
];
